# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
minimum_pre_commit_version: 3.3.0
default_install_hook_types: [pre-commit,commit-msg]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: debug-statements
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: mixed-line-ending
        args: ['-f=lf']
      - id: double-quote-string-fixer

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: ['--config=.flake8']

  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.1.1'
    hooks:
    -   id: mypy
        additional_dependencies: []

  - repo: https://github.com/espressif/conventional-precommit-linter
    rev: v1.2.0
    hooks:
      - id: conventional-precommit-linter
        stages: [commit-msg]
        args:
          - --types=bump,ci,docs,feat,fix,test
          - --subject-min-length=10
  - repo: https://github.com/myint/eradicate/
    rev: v2.1.0
    hooks:
      - id: eradicate
  - repo: https://github.com/espressif/check-copyright/
    rev: v1.0.3
    hooks:
      - id: check-copyright
        args: ['--ignore', 'ci/check_copyright_ignore.txt', '--config', 'ci/check_copyright_config.yaml']
