name: "Build"

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  build_wifi_remote:
    name: Build WiFi Remote Test
    strategy:
      matrix:
        idf_ver: ["latest", "release-v5.4", "release-v5.3"]
        test: [ { app: smoke_test, path: "test/smoke_test" }]
    runs-on: ubuntu-20.04
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Checkout protocols
        uses: actions/checkout@v3
        with:
          repository: espressif/esp-protocols
          ref: wifi_remote-v0.4.0
          sparse-checkout: |
            ci/build_apps.py
            ci/ignore_build_warnings.txt
          sparse-checkout-cone-mode: false
          path: protocols
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
            key: ${{ matrix.idf_ver }}
      - name: Build ${{ matrix.test.app }} with IDF-${{ matrix.idf_ver }}
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          pip install idf-component-manager idf-build-apps --upgrade
          python ./components/esp_wifi_remote/scripts/generate_slave_configs.py ./components/esp_wifi_remote/${{matrix.test.path}}
          python $GITHUB_WORKSPACE/protocols/ci/build_apps.py ./components/esp_wifi_remote/${{matrix.test.path}} -vv --preserve-all

  build_wifi_remote_example:
    name: Build WiFi Remote Example
    strategy:
      matrix:
        idf_ver: ["latest"]
        example: [ { app: host, path: "examples/mqtt" }, { app: slave, path: "examples/server" }]
        include:
          - idf_ver: "latest"
            example: { app: slave, path: "examples/server" }
            warning: "Warning: The smallest app partition is nearly full"

    runs-on: ubuntu-20.04
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Checkout protocols
        uses: actions/checkout@v3
        with:
          repository: espressif/esp-protocols
          ref: wifi_remote-v0.4.0
          sparse-checkout: |
            ci/build_apps.py
            ci/ignore_build_warnings.txt
          sparse-checkout-cone-mode: false
          path: protocols
      - name: Build ${{ matrix.example.app }} with IDF-${{ matrix.idf_ver }}
        env:
          EXPECTED_WARNING: ${{ matrix.warning }}
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          pip install idf-component-manager idf-build-apps --upgrade
          python $GITHUB_WORKSPACE/protocols/ci/build_apps.py ./components/esp_wifi_remote/${{matrix.example.path}} -vv --preserve-all
